const NotificationType = {
  CHAT: 'CHAT',
  ORDER_CANCELED: 'ORDER_CANCELED',
  ORDER_DECLINED: 'ORDER_DECLINED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_DONE: 'ORDER_DONE',
  NEW_ORDER: 'NEW_ORDER'
};

export default NotificationType;
